spring.application.name=zznew_Project

server.port=7890


spring.datasource.url=jdbc:mysql://localhost:3306/customer_feedback
spring.datasource.username=root
spring.datasource.password=Root@123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
